{"name": "test_verfity[data0]", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'", "trace": "self = <test_verify_data_bin.Test_verify_data object at 0x146D9268>, data = {'三字码': 'KOR', '主账号': 1000006091.0, '加点': 1.0, '国家': '南韩', ...}\n\n    @allure.story('获取组别点差等信息')\n    @pytest.mark.parametrize('data',testdata)\n    def test_verfity(self,data):\n        with allure.step('新开账号详情页'):\n            verify.enter_details_page(int(data['主账号']))\n        with allure.step('判断当前交易账号是否唯一，不唯一则跳过，唯一则验证开户信息：'):\n            if verify.is_traccount_onlyone():\n                with allure.step('存在多个交易账号，跳过此用例'):\n                    verify.closebrowser()\n                    pytest.skip()\n            else:\n                with allure.step('断言，判断当前交易账号开户信息是否与链接一致'):\n                #断言\n                    pytest.assume(verify.get_group() == data['组别'])\n                    pytest.assume(verify.get_lever() == int(data['杠杆']))\n                    pytest.assume(verify.get_spreadType() == data['点差'])\n                    pytest.assume(verify.get_markup() == int(data['加点']))\n                    pytest.assume(verify.get_currency() == data['币种'])\n>                   allure.attach(verify.screenshots('交易账号信息'),'账号信息',allure.attachment_type.PNG)\n\ndemo\\registration_process\\register_actions_bin\\test_verify_data_bin.py:61: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\_allure.py:179: in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\nC:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\nC:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\nC:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\nC:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_pytest\\listener.py:222: in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\nC:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\reporter.py:119: in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\nC:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\nC:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\nC:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <allure_commons.logger.AllureFileLogger object at 0x14656AC0>, body = None, file_name = '04fe7745-3d9d-4141-8228-1bd01be5edbe-attachment.png'\n\n    @hookimpl\n    def report_attached_data(self, body, file_name):\n        destination = os.path.join(self._report_dir, file_name)\n        with open(destination, 'wb') as attached_file:\n            if isinstance(body, text_type):\n                attached_file.write(body.encode('utf-8'))\n            else:\n>               attached_file.write(body)\nE               TypeError: a bytes-like object is required, not 'NoneType'\n\nC:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\logger.py:62: TypeError"}, "steps": [{"name": "新开账号详情页", "status": "passed", "start": 1629716992294, "stop": 1629717006784}, {"name": "判断当前交易账号是否唯一，不唯一则跳过，唯一则验证开户信息：", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"d:\\code\\tylerhub\\demo\\registration_process\\register_actions_bin\\test_verify_data_bin.py\", line 61, in test_verfity\n    allure.attach(verify.screenshots('交易账号信息'),'账号信息',allure.attachment_type.PNG)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\_allure.py\", line 179, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_pytest\\listener.py\", line 222, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\reporter.py\", line 119, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\logger.py\", line 62, in report_attached_data\n    attached_file.write(body)\n"}, "steps": [{"name": "断言，判断当前交易账号开户信息是否与链接一致", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"d:\\code\\tylerhub\\demo\\registration_process\\register_actions_bin\\test_verify_data_bin.py\", line 61, in test_verfity\n    allure.attach(verify.screenshots('交易账号信息'),'账号信息',allure.attachment_type.PNG)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\_allure.py\", line 179, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_pytest\\listener.py\", line 222, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\reporter.py\", line 119, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\logger.py\", line 62, in report_attached_data\n    attached_file.write(body)\n"}, "attachments": [{"name": "账号信息", "source": "04fe7745-3d9d-4141-8228-1bd01be5edbe-attachment.png", "type": "image/png"}], "start": 1629717008914, "stop": 1629717040586}], "start": 1629717006784, "stop": 1629717040588}], "parameters": [{"name": "data", "value": "{'国家': '南韩', '邮箱': '1100000010@uitest.com', '主账号': 1000006091.0, '三字码': 'KOR', '通过专属链接/邀请码': '', '密码': '', '地区': '', '邀请码': '', '币种': 'USD', '加点': 1.0, '杠杆': 400.0, '组别': 'demoforex2-atfx', '点差': 'Standard'}"}], "start": 1629716992294, "stop": 1629717040589, "uuid": "6a360c0b-d70f-4cb6-8d23-671e501b7e6c", "historyId": "3682f4280185b5731bc6d6e1702abf57", "testCaseId": "3f8a195e87f139f246c72806535d38a2", "fullName": "demo.registration_process.register_actions_bin.test_verify_data_bin.Test_verify_data#test_verfity", "labels": [{"name": "story", "value": "获取组别点差等信息"}, {"name": "feature", "value": "验证审核后信息"}, {"name": "parentSuite", "value": "demo.registration_process.register_actions_bin"}, {"name": "suite", "value": "test_verify_data_bin"}, {"name": "subSuite", "value": "Test_verify_data"}, {"name": "host", "value": "一台憨憨笔记本"}, {"name": "thread", "value": "21980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "demo.registration_process.register_actions_bin.test_verify_data_bin"}]}